apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackergateway
spec:
  selector:
    matchLabels:
      app: trackergateway
  template:
    metadata:
      labels:
        app: trackergateway
    spec:
      containers:
      - name: trackergateway
        image: sakthisaran/tracker_gateway:BUILDNUMBER
        env:
        - name: AUTH_SERVER_URL
          value: http://trackerauthservice:80
        - name: MAIN_SERVER_URL
          value: http://trackermainservice:80
        - name: GENERIC_SERVER_URL
          value: http://trackergenericservice:80
        - name: EMQX_SERVER_URL
          value: http://emqxdashboard:80
        - name: EMQX_SOCKET
          value: ws://emqxmqtt:8083
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: secretpasswords
              key: SPRING_PROFILE

        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
