spring:
  application:
    name: MY-EUREKA-SERVER

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /swagger/swagger.html
    defaultModelsExpandDepth: -1
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v1/auth/api-docs
        name: Auth Service
      - url: /v1/generic/api-docs
        name: GENERIC SERVICE
      - url: /v1/emqx/api-docs
        name: Tracker Service




