server:
  port: 80
logging:
  level:
    web: debug
    root: debug
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVER_URL:http://localhost:8080}
          predicates:
            - Path=/tracker/auth/**,/tracker/user/**


