server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVER_URL}
          predicates:
            - Method=GET,POST,DELETE
            - Path=/tracker/auth/**,/tracker/user/**,/v1/api-docs

        - id: tracker-manager
          uri: ${TRACKER_MANAGER}
          predicates:
            - Method=GET,POST,DELETE
            - Path=/tracker/emqx/**

        - id: emqx-socket
          uri: ${EMQX_MQTT_SOCKET}
          predicates:
            - Path=/**
          filters:
            - RewritePath=/,/mqtt