server:
  port: 80
logging:
  level:
    web: debug
    root: debug
tracker:
  validateUrl: http://localhost:81
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:81
          predicates:
            - Method=GET,POST,DELETE
            - Path=/tracker/auth/**,/tracker/user/**,/v1/auth/api-docs
          filters:
            - TokenValidationFilter

        - id: tracker-manager
          uri: http://localhost:83
          predicates:
            - Method=GET,POST,DELETE
            - Path=/tracker/emqx/**,/v1/emqx/api-docs
          filters:
            - TokenValidationFilter

        - id: generic
          uri: http://localhost:82
          predicates:
            - Method=GET,POST
            - Path=/v1/generic/api-docs,/tracker/resource/**

        - id: emqx
          uri: http://localhost:32768
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api-docs/swagger.json,/api/v5/**

        - id: emqx-socket
          uri: ws://192.168.0.108:32771
          predicates:
            - Path=/
          filters:
            - RewritePath=/,/mqtt